/**
 * Turn the screenshot originals into what the site actually ships.
 *
 * Sources live in `src/media/projects/` and are never served. This writes the
 * derived WebP into `public/projects/`, which is what both the museum textures
 * and the catalogue load.
 *
 * The reason this exists rather than Astro's `<Image>`: the same file has to be
 * reachable two ways. The catalogue is ordinary HTML and could use the asset
 * pipeline, but the museum hands the URL to a THREE.TextureLoader at runtime,
 * and that needs a real, stable path under public/. One pre-built WebP serves
 * both.
 *
 * Sizing is set by the larger of the two uses. In the museum a canvas is ~4.6m
 * wide and read from about two metres, so it covers maybe a third of a 1080p
 * screen; in the catalogue the column is ~340px CSS. 1280px wide covers both
 * with room to spare, and turns 3.0MB of PNG into roughly 400KB -- which
 * matters because the museum's Suspense boundary waits for every one of these
 * before the door will open.
 *
 * Run after adding or replacing a screenshot:
 *   npm run images
 */
import { mkdir, readdir, writeFile } from "node:fs/promises";
import { basename, extname, join } from "node:path";
import sharp from "sharp";

const SOURCE = "src/media/projects";
const OUT = "public/projects";

/** Widths are caps, not targets: nothing is ever scaled up. */
const MAX_WIDTH = { portrait: 768, default: 1280 };
const QUALITY = 80;

const sizes = {};

await mkdir(OUT, { recursive: true });

for (const file of await readdir(SOURCE)) {
  if (![".png", ".jpg", ".jpeg"].includes(extname(file).toLowerCase())) continue;

  const name = basename(file, extname(file));
  const image = sharp(join(SOURCE, file));
  const { width, height } = await image.metadata();
  const cap = MAX_WIDTH[name] ?? MAX_WIDTH.default;
  const target = Math.min(width, cap);

  const out = await image
    .resize({ width: target, withoutEnlargement: true })
    .webp({ quality: QUALITY, effort: 6 })
    .toBuffer();

  await writeFile(join(OUT, `${name}.webp`), out);

  // The catalogue needs intrinsic dimensions to reserve the right box before
  // the image arrives, and the museum needs the aspect ratio to size the canvas
  // on the wall. Both come from here so neither has to guess.
  const scaled = Math.round((height * target) / width);
  sizes[name] = [target, scaled];

  console.log(
    `${name}.webp  ${target}x${scaled}  ` +
      `${(out.length / 1024).toFixed(0)}KB  (from ${width}x${height})`,
  );
}

/*
 * The social card.
 *
 * Kept as a separate, fixed-size PNG rather than reusing a screenshot: link
 * unfurlers crop to 1.91:1 whatever you give them, and several of them still
 * will not touch WebP. 1200x630 on the gallery's own near-black is the one
 * shape every one of them handles.
 */
const card = await sharp(join(SOURCE, "portrait.png"))
  .resize({ width: 520, height: 520, fit: "cover" })
  .toBuffer();

await sharp({
  create: {
    width: 1200,
    height: 630,
    channels: 3,
    background: "#08080b",
  },
})
  .composite([{ input: card, top: 55, left: 340 }])
  .jpeg({ quality: 86, mozjpeg: true })
  .toFile("public/og.jpg");

console.log("og.jpg       1200x630");

// Emitted rather than hand-maintained: a screenshot swapped for one of a
// different shape would otherwise leave a stale aspect ratio behind, and the
// museum would stretch it across the frame without complaining.
const generated =
  `/**\n` +
  ` * Generated by scripts/optimize-images.mjs -- do not edit by hand.\n` +
  ` *\n` +
  ` * Intrinsic size of each shipped WebP, in pixels. Run \`npm run images\`\n` +
  ` * after adding or replacing a screenshot.\n` +
  ` */\n` +
  `export const IMAGE_SIZES: Record<string, [number, number]> = ${JSON.stringify(
    sizes,
    null,
    2,
  )};\n`;

await writeFile("src/data/image-sizes.ts", generated);
console.log("\nwrote src/data/image-sizes.ts");
