<template>
  <div class="bg-blue-900 text-white">
    <Nav />
    <Content />

    <div class="flex flex-col items-center">
      <select v-model="selectedOption" class="bg-yellow-600 p-2 rounded-md mb-4">
        
        <option value="option1" selected>Work</option>
        <option value="option2">Sexy Stuff</option>
        <option value="option3">Birthday</option>
        <option value="option4">Generic</option>
      </select>
    </div>

    <div class="flex justify-center max-w-md mx-auto mb-5">
      <button
        class="bg-violet-500 text-white border border-yellow-500 hover:bg-white hover:text-yellow-500 active:bg-yellow-600 font-bold uppercase px-8 py-3 rounded-full outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"
        type="button"
        @click="updateResult"
      >
        <i class="fas fa-heart"></i> Generate! <i class="fas fa-heart"></i>
      </button>
    </div>

    <div
      class="max-w-md mx-auto bg-white rounded-lg shadow-lg p-6 hover:shadow-3xl transform hover:-translate-y-3 transition duration-500"
    >
      <div class="mb-2">
        <p class="text-gray-600">Hi, I'm really sorry but today...</p>
        <div ref="text">
          <p class="text-3xl text-gray-700 my-5 py-5">{{ result }}</p>
        </div>
      </div>
      <div class="flex justify-between">
        <button @click="copyToClipboard()" class="text-gray-600">
          <i class="fas fa-copy"></i> Copy to Clipboard
        </button>
      </div>
    </div>
  </div>
  <div @click="showAlert()">
  <Footer />
</div>
</template>

<script>
import Footer from "./components/Footer.vue";
import Content from "./components/Content.vue";
import Nav from "./components/Nav.vue";
import { VueElement } from "vue";
import Swal from "sweetalert2";
import { onMounted, inject } from "vue";
const reasons = [];
const message = "Welcome! We're excited to share with you that this webpage was created by Alejo, with the assistance of ChatGPT. Excuses and code were generated by ChatGPT, Alejo made sure to do all the minor adjustements. Bye!"

export default {
  components: {
    Footer,
    Content,
    Nav,
  },

  data() {
    return {
      randomReason: "",
      selectedOption: "option1",
      option1Array: [  "Feeling unwell",
  "Taking care of a sick family member",
  "Doctor's appointment",
  "Dental appointment",
  "Mental health day",
  "Family emergency",
  "Attending a wedding",
  "Attending a funeral",
  "Moving to a new home",
  "Car broke down",
  "Pet emergency",
  "Childcare issue",
  "Attending a concert",
  "Attending a sports event",
  "Going on a vacation",
  "Caring for a newborn",
  "Taking care of an elderly relative",
  "Taking a personal day",
  "Religious holiday",
  "Voting in an election",
  "Performing jury duty",
  "Attending a job interview",
  "Visiting a friend or family member out of town",
  "Volunteering for a charity",
  "Participating in a community event",
  "Participating in a demonstration or protest",
  "Participating in something",
  "Attending a conference or seminar",
  "Taking a day to study or work on a personal project",
  "Recovering from a minor surgery or medical procedure",
  "Attending a school event for your child",
  "Helping a friend move",
  "Taking care of a personal errand",
  "Taking a mental health break",
  "Doing something for charity",
  "Attending a funeral of a friend or distant relative",
  "Taking a day for self-care",
  "Doing something creative",
  "Taking a day to organize your home",
  "Taking a day to work on a hobby",
  "Attending a religious retreat or seminar",
  "Taking a day to catch up on sleep",
  "Having a therapy session",
  "Taking a day to plan a future trip",
  "Going on a long drive or road trip",
  "Taking a day to catch up on reading or movies",
  "Taking a day to do something adventurous",
  "Taking a day to cook or bake something special",
  "Doing a one-day course or workshop",
  "Taking a day to get a massage or spa treatment",
  "Taking a day to do something athletic or outdoors",
  "Taking a day to work on your side hustle",
  "Attending a networking event",
  "Taking a day to do something you've always wanted to do",
  "My pet snake got loose and I need to find it",
  "I accidentally booked a vacation on the wrong dates",
  "I'm having car trouble and need to get it fixed",
  "My child is sick and needs to go to the doctor",
  "My house is being fumigated and I need to be out of it for the day",
  "I have an important family event to attend",
  "I have a dental appointment that can't be rescheduled",
  "I'm experiencing a personal emergency and need the day off",
  "I have to attend a court date",
  "My internet is down and I need to be home for the repair technician",
  "I have an allergic reaction to something and need medical attention",
  "I accidentally double booked myself for that day",
  "My spouse is having a medical procedure and I need to be there",
  "I have an important job interview for another company",
  "My child's school is closed and I need to be home with them",
  "I'm having plumbing issues at home that need to be addressed",
  "I have to take care of a sick family member",
  "My child is in a school play and I need to attend",
  "I'm attending a funeral out of town",
  "My doctor's appointment is running late and I won't be able to make it in",
  "I have a previously scheduled appointment with a financial advisor",
  "I have to attend a parent-teacher conference at my child's school",
  "I'm moving and need to deal with logistics",
  "My passport has been lost and I need to sort out the paperwork",
  "I have to appear in court for a jury duty summons",
  "My car has been stolen and I need to file a police report",
  "I'm attending a charity event that's been planned for months",
  "I have to deal with a landlord dispute and need to take the day off",
  "My child's school is having a field trip and I need to chaperone",
  "I need to attend a memorial service for a loved one",
  "I have to take my pet to the vet for a medical emergency",
  "I'm having a medical procedure that requires me to take the day off",
  "I have an important religious observance that I need to attend",
  "My water heater has exploded and I need to deal with the aftermath",
  "I'm participating in a once-in-a-lifetime experience",
  "I have a meeting with my lawyer that can't be rescheduled",
  "I have to attend a graduation ceremony for a family member",
  "I'm having a family reunion that's been planned for months",
  "My neighbor is having a medical emergency and I need to be there",
  "Stuck in traffic... in my dreams",
  "On a secret mission to save the world from boredom",
  "Experiencing a temporary case of amnesia, I forgot I had work today",
  "Doing my civic duty by attending a cat fashion show",
  "Lost my keys and can't find my way out of the house",
  "Volunteering at a food bank... for cupcakes",
  "Stuck in a time warp where it's always the weekend",
  "Conducting a social experiment on the effects of sleeping in on productivity",
  "Taking a mental health day to binge-watch my favorite show",
  "Caught up in a spontaneous dance party",
  "Trapped in an elevator with only a pineapple and a ukulele",
  "Embarking on a quest to find the best coffee in town",
  "Doing a community service by spreading joy and laughter on the streets",
  "Helping a friend chase their dreams by being their emotional support llama",
  "Taking a trip down memory lane and revisiting my childhood",
  "Joining a support group for people addicted to taking naps",
  "Attending a seminar on how to procrastinate better",
  "On a top-secret mission to infiltrate a rival company's snack cabinet",
  "Busy working on my lifelong dream of becoming a couch potato",
  "Attending a seminar on how to communicate better with my inner sloth",
  "Reenacting a scene from my favorite movie with my imaginary friend",
  "Trying out a new diet where I only eat donuts",
  "Practicing for the World Series of Napping",
  "Locked out of my house and can't find a way in",
  "Having an existential crisis and questioning the meaning of work",
  "Participating in a flash mob that I accidentally stumbled upon",
  "Taking a day off to celebrate National Procrastination Day",
  "Playing hooky to attend a workshop on how to make excuses",
  "On a top-secret mission to save the world from a shortage of ice cream",
  "Being held hostage by my cat who refuses to let me leave the house",
  "Training for the Olympics of Netflix binging",
  "Stuck in a parallel universe where every day is Sunday",
  "Embarking on a journey to find the perfect avocado toast",
  "Taking a break to celebrate National Sleep Day",
  "Stuck in a virtual reality game that I can't seem to beat",
  "Taking a day off to plan the perfect escape from work",
  "Volunteering at a pet shelter, because dogs need love too",
  "Taking a mental health day to focus on my well-being",
  "Busy trying to solve the world's most complicated crossword puzzle",
  "Participating in a scavenger hunt to find the meaning of life",
  "Attending a seminar on how to achieve maximum levels of procrastination",
  "On a top-secret mission to save the world from a shortage of tacos",
  "Taking a day off to prepare for the apocalypse",
  "Stuck in a time loop where every day is Monday",
  "Training to become a professional napper",
  "Having a midlife crisis and contemplating a career change",
  "Taking a break to attend a workshop on how to be lazy",
  "Embarking on a quest to find the best pizza in the city",
  "Volunteering at a charity event for the sole purpose of free food",
  "Taking a mental health day to meditate and find inner peace",
  "Busy organizing my sock drawer in alphabetical order",
  "Participating in a flash mob that I organized",
  "On a top-secret mission to find the perfect meme.",
  "Busy figuring out how to turn my daydreams into reality.",
  "Trapped in a time loop where it's always happy hour.",
  "Taking a day off to learn how to juggle flaming torches.",
  "Participating in a synchronized swim meet...in my bathtub.",
  "Stuck in a brainstorming session with my imaginary friend.",
  "Busy testing out the latest hoverboard prototype.",
  "Volunteering at a charity event for the sole purpose of petting puppies.",
  "Taking a day off to train for the World Series of Sudoku.",
  "On a mission to find the world's best burrito.",
  "Participating in a hackathon to develop the world's most efficient procrastination app.",
  "Stuck in a traffic jam...in my head.",
  "Taking a day off to learn how to play the kazoo.",
  "Busy building a fort out of office supplies.",
  "Trapped in a cycle of existential dread and contemplating the futility of work.",
  "On a top-secret mission to locate the nearest ice cream truck.",
  "Participating in a contest to see how long I can balance a spoon on my nose.",
  "Taking a day off to learn how to knit a scarf for my pet rock.",
  "Stuck in a virtual reality game where I'm a superhero who saves the world from boredom.",
  "Busy watching reruns of The Office to learn how to be a better employee.",
  "Trapped in a thought loop where I'm debating whether I should quit my job and become a professional finger painter.",
  "Taking a day off to attend a seminar on how to become a master of doing nothing.",
  "On a mission to find the world's greatest cup of coffee.",
  "Participating in a hot dog eating contest...with vegan hot dogs.",
  "Stuck in a daydream where I'm a famous rapper and can't stop freestyling.",
  "Busy practicing my interpretive dance moves for the office talent show.",
  "Trapped in a cycle of indecision and can't decide whether to go to work or call in sick.",
  "Taking a day off to attend a workshop on how to be more spontaneous.",
  "On a top-secret mission to save the world from a shortage of guacamole.",
  "Participating in a costume contest dressed as a giant pencil.",
  "Busy perfecting my air guitar skills for the company karaoke party.",
  "Trapped in a time loop where it's always my birthday.",
  "Taking a day off to learn how to speak in whale language.",
  "On a mission to find the world's most comfortable pair of pants.",
  "Participating in a staring contest with my reflection in the mirror.",
  "Stuck in a daydream where I'm the star of my own reality show.",
  "Busy building a pillow fort and watching cartoons all day.",
  "Trapped in a cycle of existential dread and questioning the meaning of life.",
  "Taking a day off to learn how to make balloon animals.",
  "On a top-secret mission to locate the nearest coffee shop with a unicorn theme.",
  "Participating in a hula-hoop contest...with a flaming hoop.",
  "Busy practicing my magic tricks for the company talent show.",
  "Trapped in a thought loop where I'm trying to decide what to eat for lunch.",
  "Stuck in a daydream where I'm a famous explorer and have to find a lost city.",
  "Busy training for the company's annual three-legged race.",
  "Trapped in a cycle of overthinking and can't decide what to have for lunch.",
  "Taking a day off to attend a workshop on how to speak to plants.",
  "On a mission to find the world's best taco.",
  "Participating in a contest to see who can fold the most origami cranes in an hour.",
  "Stuck in a daydream where I'm a world-famous chef and have to create the perfect dish.",
  "Busy organizing a charity event to raise money for a local kitten adoption agency.",
  "Trapped in a thought loop where I'm trying to remember the lyrics to the Macarena.",
  "Taking a day off to attend a seminar on how to be a professional slacker.",
  "On a top-secret mission to find the world's best cup of coffee.",
  "Participating in a competition to see who can balance the most office supplies on their nose.",
  "Stuck in a daydream where I'm a famous fashion designer and have to create a new line of clothes.",
  "Busy practicing my juggling skills for the office talent show.",
  "Trapped in a cycle of indecision and can't decide which episode of The Office to watch.",
  "Taking a day off to learn how to meditate like a Buddhist monk.",
  "On a mission to find the world's best smoothie.",
  "Participating in a game of human knot with my friends.",
  "Stuck in a daydream where I'm a famous magician and have to perform for a royal family.",
  "Busy organizing a charity event to raise money for my imaginary friend's therapy.",
  "Trapped in a thought loop where I'm trying to remember the name of my childhood crush.",
  "Taking a day off to attend a seminar on how to train my goldfish to do tricks.",
  "On a top-secret mission to find the world's best mac and cheese.",
  "Participating in a competition to see who can build the tallest tower out of playing cards.",
  "Stuck in a daydream where I'm a famous novelist and have to finish my latest book.",
  "Busy practicing my interpretive dance routine for the office talent show.",
  "Trapped in a cycle of indecision and can't decide which pizza place to order from.",
  "Taking a day off to learn how to hula hoop like a pro.",
  "On a mission to find the world's best ice cream sundae.",
  "Participating in a game of office chair volleyball.",
  "Stuck in a daydream where I'm a famous artist and have to paint a mural for a museum.",
  "Busy organizing a charity event to raise money for a local unicorn sanctuary.",
  "Trapped in a thought loop where I'm trying to remember the name of the guy who sits next to me.",
  "Taking a day off to attend a seminar on how to be a better time traveler.",
  "On a top-secret mission to find the world's best fried chicken.",
  "Participating in a competition to see who can solve the most Rubik's cubes in an hour.",
  "Stuck in a daydream where I'm a famous astronaut and have to save a space station from aliens.",
  "Busy practicing my yodeling skills for the office talent show.",
  "Trapped in a cycle of indecision and can't decide which Netflix show to watch.",
  "Taking a day off to learn how to train my dog to fetch me coffee.",
  "On a mission to find the world's best sushi.",
  "Participating in a game of office chair basketball.",
  "Busy learning how to speak Klingon for a Star Trek convention.",
  "Trapped in a daydream where I'm a superhero and have to save the world from evil robots.",
  "Taking a day off to attend a workshop on how to write a bestselling novel in 24 hours.",
  "On a mission to find the world's best burger joint.",
  "Participating in a contest to see who can make the best balloon animals.",
  "Stuck in a daydream where I'm a famous DJ and have to mix music for a huge crowd.",
  "Busy organizing a charity event to raise money for a local llama rescue.",
  "Trapped in a thought loop where I'm trying to remember if I turned off the stove.",
  "Taking a day off to attend a seminar on how to be a professional procrastinator.",
  "On a top-secret mission to find the world's best hot wings.",
  "Participating in a competition to see who can eat the most donuts in 5 minutes.",
  "Stuck in a daydream where I'm a famous racecar driver and have to win the championship.",
  "Busy practicing my kazoo skills for the office talent show.",
  "Trapped in a cycle of indecision and can't decide which color to paint my nails.",
  "Taking a day off to learn how to play the accordion like a pro.",
  "On a mission to find the world's best falafel.",
  "Participating in a game of office chair soccer.",
  "Stuck in a daydream where I'm a famous movie director and have to shoot the next blockbuster.",
  "Busy organizing a charity event to raise money for a local unicorn breeding program.",
  "Trapped in a thought loop where I'm trying to remember if I left the iron on.",
  "Taking a day off to attend a seminar on how to be a professional napper.",
  "On a top-secret mission to find the world's best BBQ ribs.",
  "Participating in a competition to see who can eat the most tacos in 10 minutes.",
  "Stuck in a daydream where I'm a famous astronaut and have to save the Earth from an asteroid.",
  "Busy practicing my spoon playing skills for the office talent show.",
  "Trapped in a cycle of indecision and can't decide which shoes to wear.",
  "Taking a day off to learn how to speak to dolphins.",
  "On a mission to find the world's best fried rice.",
  "Participating in a game of office chair hockey.",
  "Stuck in a daydream where I'm a famous fashion designer and have to create a line of clothes for dogs.",
  "Busy organizing a charity event to raise money for a local giraffe rehabilitation center.",
  "Trapped in a thought loop where I'm trying to remember if I locked the front door.",
  "Taking a day off to attend a seminar on how to be a professional daydreamer.",
  "On a top-secret mission to find the world's best pizza toppings.",
  "Participating in a competition to see who can eat the most cupcakes in 5 minutes.",
  "Stuck in a daydream where I'm a famous spy and have to save the world from an evil villain.",
  "Busy practicing my beatboxing skills for the office talent show.",
  "Trapped in a cycle of indecision and can't decide which hairstyle to try next.",
  "Taking a day off to learn how to do a backflip.",
  "On a mission to find the world's best pad thai.",
  "Participating in a game of office chair dodgeball.",
  "Stuck in a daydream where I'm a famous musician and have to perform a sold-out concert.",
  "Busy organizing a charity event to raise money for a local unicorn adoption agency.",
  "Stuck in a daydream where I'm a famous explorer and have to find a lost city.",
  "Busy training for the company's annual three-legged race.",
  "Trapped in a cycle of overthinking and can't decide what to have for lunch.",
  "Taking a day off to attend a workshop on how to speak to plants.",
  "On a mission to find the world's best taco.",
  "Participating in a contest to see who can fold the most origami cranes in an hour.",
  "Stuck in a daydream where I'm a world-famous chef and have to create the perfect dish.",
  "Busy organizing a charity event to raise money for a local kitten adoption agency.",
  "Trapped in a thought loop where I'm trying to remember the lyrics to the Macarena.",
  "Taking a day off to attend a seminar on how to be a professional slacker.",
  "On a top-secret mission to find the world's best cup of coffee.",
  "Participating in a competition to see who can balance the most office supplies on their nose.",
  "Stuck in a daydream where I'm a famous fashion designer and have to create a new line of clothes.",
  "Busy practicing my juggling skills for the office talent show.",
  "Trapped in a cycle of indecision and can't decide which episode of The Office to watch.",
  "Taking a day off to learn how to meditate like a Buddhist monk.",
  "On a mission to find the world's best smoothie.",
  "Participating in a game of human knot with my friends.",
  "Stuck in a daydream where I'm a famous magician and have to perform for a royal family.",
  "Busy organizing a charity event to raise money for my imaginary friend's therapy.",
  "Trapped in a thought loop where I'm trying to remember the name of my childhood crush.",
  "Taking a day off to attend a seminar on how to train my goldfish to do tricks.",
  "On a top-secret mission to find the world's best mac and cheese.",
  "Participating in a competition to see who can build the tallest tower out of playing cards.",
  "Stuck in a daydream where I'm a famous novelist and have to finish my latest book.",
  "Busy practicing my interpretive dance routine for the office talent show.",
  "Trapped in a cycle of indecision and can't decide which pizza place to order from.",
  "Taking a day off to learn how to hula hoop like a pro.",
  "On a mission to find the world's best ice cream sundae.",
  "Participating in a game of office chair volleyball.",
  "Stuck in a daydream where I'm a famous artist and have to paint a mural for a museum.",
  "Busy organizing a charity event to raise money for a local unicorn sanctuary.",
  "Trapped in a thought loop where I'm trying to remember the name of the guy who sits next to me.",
  "Taking a day off to attend a seminar on how to be a better time traveler.",
  "On a top-secret mission to find the world's best fried chicken.",
  "Participating in a competition to see who can solve the most Rubik's cubes in an hour.",
  "Stuck in a daydream where I'm a famous astronaut and have to save a space station from aliens.",
  "Busy practicing my yodeling skills for the office talent show.",
  "Trapped in a cycle of indecision and can't decide which Netflix show to watch.",
  "Taking a day off to learn how to train my dog to fetch me coffee.",
  "On a mission to find the world's best sushi.",
  "Participating in a game of office chair basketball.",],
      option2Array: ["I'm on a 24-hour sex fast.",
"I'm allergic to your aftershave/perfume.",
"Sorry, I promised my cat we'd have a movie night tonight.",
"I have a rare condition where my body turns into a jellyfish during intercourse.",
"I'm saving myself for the apocalypse.",
"I can't tonight, I have to do my taxes.",
"I just remembered I have to clean my oven tonight.",
"I've decided to become a monk/nun.",
"My chakras aren't aligned properly tonight.",
"Sorry, I'm on a juice cleanse and I can't have any 'solid' foods tonight.",
"I'm waiting for the stars to align.",
"I'm too busy playing video games.",
"I'm allergic to your touch.",
"I have a phobia of nakedness.",
"My aura is telling me 'no'.",
"Sorry, I just ate garlic bread and my breath is lethal.",
"I'm saving my energy for my marathon training.",
"I can't tonight, I have to catch up on my knitting.",
"I'm not in the mood, I just read a really sad book.",
"I'm afraid I might accidentally call out the wrong name.",
"I'm on a diet and I can't have any fun tonight.",
"Sorry, I just got a spray tan and I don't want to ruin my sheets.",
"I'm afraid my dog might get jealous.",
"I can't, I need to organize my sock drawer.",
"I'm too focused on my career right now.",
"I'm actually a superhero and I'm needed elsewhere tonight.",
"I'm in the middle of a game of chess and I can't leave it unfinished.",
"I just started a new meditation routine and I don't want to disrupt my energy.",
"I'm trying to break my record of consecutive nights of no sex.",
"I can't, I'm in the middle of a jigsaw puzzle and I can't lose my concentration.",
"I have a rare disease where physical exertion can cause uncontrollable laughter.",
"I'm afraid I might accidentally summon a demon.",
"I'm trying to save water by not taking a shower tonight.",
"I can't tonight, I need to finish binge-watching my favorite show.",
"I'm sorry, I just found out I'm a fish",],
      option3Array: [
 "Sorry, I can't make it to your birthday party because I'm allergic to cake!",
 "I'd love to come to your birthday party, but I just remembered that I have to organize my sock drawer that day.",
 "I have a bad case of birthday-phobia.",
 "I can't come to your birthday party, I promised my cat we'd have a movie night that day.",
 "Sorry, I have to wash my hair that day. It's a really long process!",
 "I can't come to your birthday party because I'm busy washing my pet rock.",
 "I'm really sorry, but my psychic told me it's not a good day for me to be around people.",
 "I'm trying to cut down on fun.",
 "I have a rare condition where I break out in hives if I go to birthday parties.",
 "I can't come to your birthday party because I have to reorganize my spice rack that day.",
 "Sorry, I have to return some videotapes that day.",
 "I'd love to come to your birthday party, but I'm on house arrest.",
 "I can't come to your birthday party because I have a really important staring contest that day.",
 "I'd love to come to your birthday party, but I just realized that I have to alphabetize my bookshelf.",
 "I can't come to your birthday party because I have to prepare for a zombie apocalypse.",
 "Sorry, I'm busy that day burning all my childhood photos.",
 "I can't come to your birthday party because I'm in the middle of a GoT marathon.",
 "I'm sorry, but I'm saving my socializing energy for my parole hearing.",
 "I can't come to your birthday party because I have a really important staring contest that day.",
 "Sorry, I'm going to be too busy playing Minecraft all day.",
 "I can't come to your birthday party because I promised my goldfish we'd have a movie night that day.",
 "Sorry, I can't come to your birthday party because I have to wash my hair (my eyebrows get really dirty too).",
 "I'd love to come to your birthday party, but I have to do my laundry that day.",
 "I'm really sorry, but I have to spend the day planning my imaginary wedding.",
 "I can't come to your birthday party because I'm allergic to balloons.",
 "I'm sorry, but I'm in the middle of a 72-hour Simpsons marathon.",
 "I can't come to your birthday party because I'm busy training for a hot dog eating contest.",
 "Sorry, I can't come to your birthday party because I have to alphabetize my movie collection.",
 "I'd love to come to your birthday party, but I have to catch up on my knitting that day.",
 "I can't come to your birthday party because I have to wash my hair (my beard gets really dirty too).",
 "I'm really sorry, but I'm in the middle of a beard grooming session.",
 "I can't come to your birthday party because I promised my pet rock we'd have a movie night that day.",
 "Sorry, I can't come to your birthday party because I have to organize my spice rack that day.",
 "I'm sorry, but I'm in the middle of a deep sea fishing trip.",
 "I can't come to your birthday party because I'm allergic to balloons and cake.",
 "Sorry, I can't come to your birthday party because I have to practice my underwater basket weaving.",
 "I can't come to your birthday party because I have to clean my collection of rare vintage socks.",
 "I'm sorry, but I can't make it to your birthday party because I have to clean out my garage that day.",
 "I'd love to come to your birthday party, but I have to count all the blades of grass in my yard that day.",
 "I can't come to your birthday party because I'm in the middle of a game of Jenga that's been going on for three days straight.",
 "Sorry, I can't make it to your birthday party because I have to organize my collection of rubber ducks.",
 "I can't come to your birthday party because I'm allergic to candles.",
 "Sorry, I can't make it to your birthday party because I have to clean out my closet that day.",
 "I'd love to come to your birthday party, but I'm on house arrest for impersonating a unicorn.",
 "I can't come to your birthday party because I have to train my pet rock to do tricks that day.",
 "Sorry, I can't make it to your birthday party because I have to alphabetize my CD collection.",
 "I can't come to your birthday party because I have a fear of balloons popping.",
 "Sorry, I can't make it to your birthday party because I have to reorganize my collection of antique spoons.",
 "I'd love to come to your birthday party, but I'm in the middle of a deep sea diving expedition.",
 "I can't come to your birthday party because I'm busy practicing my stand-up comedy routine.",
 "Sorry, I can't make it to your birthday party because I have to clean out my fish tank that day.",
 "I can't come to your birthday party because I have to re-watch all the Harry Potter movies in one sitting.",
 "Sorry, I can't make it to your birthday party because I have to reorganize my collection of rare stamps.",
 "I'd love to come to your birthday party, but I have to groom my pet rock's hair that day.",
 "I can't come to your birthday party because I'm in the middle of a game of Twister with my imaginary friends.",],
      result: "",
    };
  },
  mounted() {
    this.generateRandomReason();
    this.updateResult();
  },
  methods: {
    generateRandomReason() {
      const randomIndex = Math.floor(Math.random() * reasons.length);
      this.randomReason = reasons[randomIndex];
    },
    copyToClipboard() {
      const text = this.$refs.text.innerText;
      const textarea = document.createElement("textarea");
      textarea.value = text;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      Swal.fire("Excuse copied to clipboard! Enjoy!");
    },
    showAlert(){
      Swal.fire(message);
    },
    updateResult() {
      if (this.selectedOption === "option1") {
        this.result =
          this.option1Array[
            Math.floor(Math.random() * this.option1Array.length)
          ];
      } else if (this.selectedOption === "option2") {
        this.result =
          this.option2Array[
            Math.floor(Math.random() * this.option2Array.length)
          ];
      } else if (this.selectedOption === "option3") {
        this.result =
          this.option3Array[
            Math.floor(Math.random() * this.option3Array.length)
          ];
        } else if (this.selectedOption === "option4") {
        this.result =
          this.option1Array[
            Math.floor(Math.random() * this.option1Array.length)
          ];
      } else {
        this.result = "";
      }
    },
  },
};
</script>

<style scoped>
.hover\:shadow-3xl:hover {
  box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);
}

.transform\:hover\:translate-y-1:hover {
  transform: translateY(-1rem);
}
</style>
