/**
 * Generated by scripts/optimize-images.mjs -- do not edit by hand.
 *
 * Intrinsic size of each shipped WebP, in pixels. Run `npm run images`
 * after adding or replacing a screenshot.
 */
export const IMAGE_SIZES: Record<string, [number, number]> = {
  "acelock": [
    1280,
    854
  ],
  "chiikawabiyori": [
    1280,
    700
  ],
  "play-reversi": [
    1280,
    697
  ],
  "portrait": [
    768,
    768
  ],
  "tegaru": [
    1280,
    686
  ]
};
